// test4-preact-6-11/src/pages/test1.tsx
import { useEffect, useRef } from "preact/hooks";
import * as THREE from "three";
import { OrbitControls } from "three/examples/jsm/Addons.js";
import gsap from "gsap";

export default function Test1() {
  const test1 = useRef<HTMLDivElement | null>(null);
  const { scene, renderer, camera } = init();
  const controls = new OrbitControls(camera, renderer.domElement);

  const cubeGeometry = new THREE.BoxGeometry(1, 1, 1);
  const cubeMaterial = new THREE.MeshBasicMaterial({
    color: 0x00ff00
  });
  const cube = new THREE.Mesh(cubeGeometry, cubeMaterial);

  const clock = new THREE.Clock();
  /* 
    ease变化过程,去gsap文档寻找调试 https://gsap.com/docs/v3/Eases/CustomEase
  */
  const cpa = gsap.to(cube.position, {
    x: 5,  // x运动到5
    duration: 2, // 2s一次
    repeat: -1, // 无限循环
    yoyo: true, // 往返运动
    ease: "back.out(1.7)",
    onStart: () => {
      console.log("start");
    },
    onComplete: () => {
      console.log("complete");
    }
  });

  gsap.to(cube.rotation, {
    x: 2 * Math.PI, // 旋转一周
    duration: 2, // 2s一次
    repeat: -1, // 无限循环
    ease: "bounce.out",
    onStart: () => {
      console.log("start");
    }
  });

  window.addEventListener("dblclick", () => {
    if(cpa.isActive()){
      cpa.pause();
    }else{
      cpa.resume();
    }
    console.log(cpa);
  });

  scene.add(cube);
  scene.add(new THREE.AxesHelper(15));
  scene.add(new THREE.GridHelper(10, 10));

  function animate() {
    controls.update();
    renderer.render(scene, camera);
    requestAnimationFrame(animate);
  }

  function ResizeWindow() {
    camera.aspect = window.innerWidth / window.innerHeight;
    camera.updateProjectionMatrix();
    renderer.setSize(window.innerWidth, window.innerHeight);
  }

  useEffect(() => {
    if (test1.current) {
      test1.current.appendChild(renderer.domElement);
      animate();
      window.addEventListener('resize', ResizeWindow);
    }
    return () => {
      window.removeEventListener('resize', ResizeWindow);
    }
  }, []);

  return (<>
    <div ref={test1}></div>
  </>);
}

function init() {
  const camera = new THREE.PerspectiveCamera(75, window.innerWidth / window.innerHeight, 0.1, 1000);
  camera.position.set(0, 5, 5);
  camera.lookAt(0, 0, 0);

  const scene = new THREE.Scene();

  const renderer = new THREE.WebGLRenderer({
    antialias: true
  });
  renderer.setSize(window.innerWidth, window.innerHeight);

  return { scene, renderer, camera };
}

// test3-vue-4-5/src/pages/test1.vue
<template>
  <div ref="test1"></div>
</template>

<script setup lang="ts">
import { onMounted, onUnmounted, ref } from "vue";
import { OrbitControls } from "three/examples/jsm/Addons.js";
import * as THREE from "three";
const test1 = ref<HTMLDivElement | null>(null);

const scene = new THREE.Scene();

const camera = new THREE.PerspectiveCamera(
  75,
  window.innerWidth / window.innerHeight,
  0.1,
  1000
);

// 渲染器
const renderer = new THREE.WebGLRenderer();
renderer.setSize(window.innerWidth, window.innerHeight);

const controls = new OrbitControls(camera, renderer.domElement);

// 设置相机位置
camera.position.z = 5;
camera.position.y = 5;
// camera.lookAt(cube.position);
camera.lookAt(0, 0, 0);

// box几何体
const geometry = new THREE.BoxGeometry(1, 1, 1);
const material = new THREE.MeshBasicMaterial({ color: 0x00ff00 }); // 材质
const cube = new THREE.Mesh(geometry, material); // 网格
// 画一个线框
const edgeGeometry = new THREE.EdgesGeometry(geometry);
const edgeMaterial = new THREE.LineBasicMaterial({ color: 0x0000ff });
const line = new THREE.LineSegments(edgeGeometry, edgeMaterial);
cube.add(line);

scene.add(cube);
scene.add(new THREE.AxesHelper(10));
scene.add(new THREE.GridHelper(10, 10));
scene.background = new THREE.Color(0xffeeee);

window.addEventListener("resize", function () {
  camera.aspect = window.innerWidth / window.innerHeight;
  camera.updateProjectionMatrix();
  renderer.setSize(window.innerWidth, window.innerHeight);
});

function animate() {
  controls.update();
  requestAnimationFrame(animate);
  cube.rotation.x += 0.01;
  cube.rotation.y += 0.01;
  cube.rotation.z += 0.01;
  renderer.render(scene, camera);
}

const windowResize = () => {
  camera.aspect = window.innerWidth / window.innerHeight;
  camera.updateProjectionMatrix();
  renderer.setSize(window.innerWidth, window.innerHeight);
};

onMounted(() => {
  if (!test1.value) return;
  test1.value.appendChild(renderer.domElement);
  animate();
  window.addEventListener("resize", windowResize);
});

onUnmounted(() => {
  window.removeEventListener("resize", windowResize);
});
</script>

<style scoped></style>
